### ISSUE TITLE
Implement as Extensions of Collections rather than struct

### ISSUE THREAD

**Issue by claudio-vellage** [almata/Combinatorics#3]
Hey there, this repository implements exactly what I've been looking for, but I didn't really like the fact that it's implemented with a struct and generic static functions.

I've swiftly (hehe) implemented a protocol-oriented version of the permutationsWithRepetition function as an extension of the Collection type. Here's the code for a small working example:

```
let set : Set = [true,false]
let array : Array = [true,false]

extension Collection {
    func permutationsWithRepetition(length n:UInt) -> [[Element]] {
        guard n > 0 else {
            return [[]]
        }
        
        return self.map{element in self.permutationsWithRepetition(length: n - 1).map{[element] + $0}}.reduce([],+)
    }
}

print(set.permutationsWithRepetition(length: 2))
print(array.permutationsWithRepetition(length: 2))
```

Is there a reason why you've chosen static functions? What do you think about using protocol extensions instead? If you're interested, I'll gladly help porting the existing code to extensions.

CV

**Comment by almata** [comment]
A reason... mmmh... yes, the reason is my Swift skills weren't probably as sharp as they should when I wrote this small library. Let me have a look at your suggestion, it looks interesting in principle.

**Comment by hebiao6446** [comment]
WELL DONE , THINKS !!!

**Comment by claudio-vellage** [comment]
Since this repository seems to be no longer maintained, would you mind if I rewrite your code in a fashion similar to my example above and send you a pull request when I'm done? I want to include these functions in a larger framework I'm currently working on. Of course, I'd credit you as the original author.

**Comment by almata** [comment]
Sure thing. Sorry I should have told you something before, my bad. Feel free to rewrite whatever is required, absolutely.
